MyEC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SecurityGroupIds:
      - !Ref MySecurityGroup
    ImageId: ami-0acd9fd39de089f9b  # Latest Amazon Linux 2 AMI for eu-west-1
    Tags:
      - Key: Name
        Value: CF-EC2-Lab
