AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Lab - EC2 with Security Group

Resources:

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref MySecurityGroup
      ImageId: ami-08b6a2983df6e9e25 # Amazon Linux 2 in us-east-1
      Tags:
        - Key: Name
          Value: CF-EC2-Lab

