MyEC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    SecurityGroupIds:
      - !Ref MySecurityGroup
    ImageId: ami-08b6a2983df6e9e25  # <-- updated for eu-west-1
    Tags:
      - Key: Name
        Value: CF-EC2-Lab
